version: '3.7'
services: 
  job: 
    build: 
      context: ../job 
      dockerfile: Dockerfile
    command: --ISCAgent false --monitorCPF false
    ports:
      - 52873:52773
      - 9103:1972
    environment:
      - TZ=JST-9
      - ISC_CPF_MERGE_FILE=/ISC/merge.cpf
    volumes:
      - ./:/ISC     
    networks:
      - iris-tier
      
  task: 
    build: ../task
    command: --ISCAgent false --monitorCPF false
    ports:
      - 52874:52773
      - 9104:1972
    environment:
      - TZ=JST-9
      - ISC_CPF_MERGE_FILE=/ISC/merge.cpf
    volumes:
      - ./:/ISC     
    networks:
      - iris-tier

  task2: 
    build: ../task
    command: --ISCAgent false --monitorCPF false
    ports:
      - 9205:52773
      - 9105:1972
    environment:
      - TZ=JST-9
      - ISC_CPF_MERGE_FILE=/ISC/merge.cpf
    volumes:
      - ./:/ISC
    networks:
      - iris-tier

  sftp:
    image: atmoz/sftp
    hostname: sftp
    volumes:
    - ../sftp/upload:/home/foo/upload
    - ../sftp/users.conf:/etc/sftp/users.conf:ro 
    environment:
    - TZ=JST-9
    networks:
    - iris-tier

networks:
  iris-tier:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24

