ROUTINE test4
main(p1="abc",halttime=0) public {
	;
	Write "You need to open WF and accept it to proceed.",!
	;
	Set tSC = ##class(Ens.Director).CreateBusinessService("Initiator",.tService)
	If ($IsObject(tService)) {
		Set input=##class(Task.Request.CallJob).%New()
		Set input.JobName="Job4"
		Set input.P1=p1
		Set input.P2=halttime
		Set tSC = tService.ProcessInput(input,.output)
		zw output
	}
}