ROUTINE deadlock
main() public {
	// https://docs.intersystems.com/iris20231/csp/docbook/Doc.View.cls?KEY=ECONFIG_PoolSize
	// https://docs.intersystems.com/iris20231/csp/docbook/DocBook.UI.Page.cls?KEY=EGDV_busproc#EGDV_busproc_principles
	// Is deadlock here really a deadlock?
	Set tSC = ##class(Ens.Director).CreateBusinessService("Direct",.tService)
	If ($IsObject(tService)) {
		Set req=##class(Ens.Request).%New()
		Set tSC = tService.ProcessInput(req,.res)
		zw res
	}
}